#+title: TRAMP-yadm
#+author: seanfarley

#+html: <p><img src="https://img.shields.io/badge/Emacs-26.1+-blueviolet.svg?logo=GNU%20Emacs&logoColor=white">
#+html: <img src="https://img.shields.io/badge/license-GPL_3-green.svg">
#+html: <a href="https://github.com/seanfarley/tramp-yadm/actions?query=workflow%3ACI"><img src="https://github.com/seanfarley/tramp-yadm/workflows/CI/badge.svg"></a></p>

=tramp-yadm= adds an Emacs [[http://www.gnu.org/software/tramp/][TRAMP]] method for accessing your [[https://yadm.io][yadm]] dotfiles. This
package adds support for [[http://magit.vc][magit]] and [[https://projectile.mx][projectile]] as well.

* Installation
For [[http://github.com/doomemacs/doomemacs][Doom Emacs]] users, just add to your config,

#+begin_src emacs-lisp
(package! tramp-yadm
  :recipe (:host github :repo "seanfarley/tramp-yadm"))
#+end_src

Otherwise, do the =load-path= and =require= dance. If you want to speed up magit by
having it not recursive list untracked files from your home directory, you'll
need to call =tramp-yadm-register=. For example, I use the following,

#+begin_src emacs-lisp
(use-package! tramp-yadm
  :defer t
  :init
  (after! magit
    (tramp-yadm-register)))
#+end_src

* Usage
Open your =yadm= dotfiles files by prepending =/yadm::~= to the file, or by adding
this snippet to your config.

#+begin_src emacs-lisp
(add-to-list 'projectile-known-projects "/yadm::~")
#+end_src

* Known issues

** =Remote file error: Forbidden reentrant call of Tramp=
When using multiple processes such as =flycheck=, there is occassionally a
reentrant error.

** =git-gutter= not turning on automatically
The needs more investigate but it might be in how =git-gutter= is checking for a
git repo.

*** If /yadm::~ is the first (and only) project loaded, git-gutter will display ascii and not unicode
Not sure about this one.

** projectile history list is not saved
If fixed, this would eliminate or greatly modify the usage section.
